### ISSUE TITLE
Host the game somewhere on the internet

### ISSUE THREAD

**Issue by BurningKarl** [sachinsshetty/tasty-assassin#1]
I'd recommend itch.io, because it would fit perfectly and I hope it's free. Maybe I'll do it myself.

In the meantime, I hosted it on my raspberry pi:
https://debentured-zebra-0226.dataplicity.io/tasty-assassin/ 
so I can show it to my friends. You are invited to share the link, but I don't guarantee, that it'll stay there longer than a week.

I had fun doing this game jam with you, maybe we will see each other at the next one :)

**Comment by sachinsshetty** [comment]
The game should now technically work at
sachinsshetty.github.io/tasty-assassin 

Changes made
* Go to settings page
* Set github-pages to master repo

Please fork your own repo and test the same.

**Comment by sachinsshetty** [comment]
Hosted on sachinsshetty.github.io/tasty-assassin
